language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - 7.1

services:
  - mysql

before_script:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.virtualcomplete vcs https://github.com/virtualcomplete/user-extension.git
  - composer require virtualcomplete/user-extension dev-master
  - cp ./vendor/virtualcomplete/user-extension/test_build/config/.env ./
  - php artisan key:generate
  - rm -f ./database/migrations/*.php
  - cp ./vendor/virtualcomplete/user-extension/test_build/migrations/* ./database/migrations/
  - cp ./vendor/virtualcomplete/user-extension/migrations/* ./database/migrations/
  - mysql -e 'CREATE DATABASE laravel;'
  - php artisan migrate
  - cp ./vendor/virtualcomplete/user-extension/test_build/seeds/* ./database/seeds/
  - composer dump-autoload
  - php artisan db:seed --class="UserSeeder"
  - cp ./vendor/virtualcomplete/user-extension/tests/*Test.php ./tests/


script: phpunit
